### ISSUE TITLE
Fails for Blender 2.82a

### ISSUE THREAD

**Issue by TennisGazelle** [panmari/stanford-shapenet-renderer#25]
When running on Blender 2.82a, the following error shows up after running the following command (may just be a dependency missing issue somehow)

```bash
<path-to-blender-executable> -b --python scripts/obj-render.py -- --output_folder imgs/out/ blender/models/curve-skeleton-cube.obj
```

can you update the requirements.txt and the code for it to work on 2.82 or whatever's LTS?

**Comment by mvoelk** [comment]
Which error?

https://github.com/mvoelk/stanford-shapenet-renderer should also run with 2.82a.

**Comment by TennisGazelle** [comment]
# the objects (and their respective dirs exist as):
```
├─ blender/
│   └──models/
│       └──curve-skeleton-cube.obj
├─ imgs/
│   └──out/ # exists
└─ scripts/
    └──obj_render.py
```

# running the command 

```
> /Applications/Blender.app/Contents/MacOS/Blender -b --python scripts/obj-render.py -- --output_folder imgs/out/ blender/models/curve-skeleton-cube.obj 
Blender 2.81 (sub 8) (hash 4764362ebb91 built 2019-09-08 01:01:41)
Read prefs: /Users/daniellopez/Library/Application Support/Blender/2.81/config/userpref.blend
found bundled python: /Applications/Blender.app/Contents/Resources/2.81/python
Traceback (most recent call last):
  File "/Users/daniellopez/dev/blender-pipeline/scripts/obj-render.py", line 41, in <module>
    bpy.context.scene.render.layers["RenderLayer"].use_pass_normal = True
AttributeError: 'RenderSettings' object has no attribute 'layers'

Blender quit
```

when commenting out line 41 (and line 42, which also references `layers`, i get this error:
```bash
/Applications/Blender.app/Contents/MacOS/Blender -b --python scripts/obj-render.py -- --output_folder imgs/out/ blender/models/curve-skeleton-cube.obj 
Blender 2.81 (sub 8) (hash 4764362ebb91 built 2019-09-08 01:01:41)
Read prefs: /Users/daniellopez/Library/Application Support/Blender/2.81/config/userpref.blend
found bundled python: /Applications/Blender.app/Contents/Resources/2.81/python
Traceback (most recent call last):
  File "/Users/daniellopez/dev/blender-pipeline/scripts/obj-render.py", line 87, in <module>
    links.new(render_layers.outputs['Color'], albedo_file_output.inputs[0])
KeyError: 'bpy_prop_collection[key]: key "Color" not found'

Blender quit
```

# side note

please note that I'm not particularly versed in `bpy` and it's relation to the scene when being interpreted (like, i realize it's run-timed based, but idk how the internal backend works)

**Comment by mvoelk** [comment]
You could try the fork I mentioned in my last comment ;)

In blender, they replaced the concept of 'render layers' with that of 'view layers'...

**Comment by TennisGazelle** [comment]
sorry for the late reply, i ended up using that fork and it's working just fine.

Thanks for the guidance and thanks for the update, @mvoelk ! It works just fine on [my repo](https://github.com/TennisGazelle/blender-pipeline)

[Relevant PR Link here.](https://github.com/TennisGazelle/blender-pipeline/pull/13)

**Comment by panmari** [comment]
Merged PR #24, so should be working now.
